main: dev.projectg.geyserhub.GeyserHub
name: ${project.name}
version: ${project.version}
api-version: 1.14
description: A simple lobby plugin
softdepend:
  - PlaceholderAPI

commands:
  ghub:
    description: General command
    permission: geyserhub.main

permissions:
  geyserhub.main:
    description: Access to the base command /ghub. Opens the default form if a player runs the command.
    default: true
  geyserhub.reload:
    description: Access to /ghub reload
    default: op
  geyserhub.blockbreak:
    description: Allows player to break blocks
    default: op
  geyserhub.blockplace:
    description: Allows player to place blocks
    default: op
